### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tsuguhide** [tsuguhide/furima-29367#10]
# URL
https://furima-29367.herokuapp.com/

# パスワード等
Basic認証[ID:furima , pass:29367]

出品者[メール: sample@gmail.com , パスワード: asdfgh1 ]
購入者[メール: buy@gmail.com , パスワード: asdfgh1 ]
購入用カード[番号: 4242424242424242 , 期限:12/24 , CVC:123 ]

**Comment by mo1015** [comment]
中澤さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！

※**補足**　購入済の商品であっても、出品者が商品編集と削除ができてしまいます。可能であればできないように修正しましょう！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by tsuguhide** [comment]
ありがとうございました！！
